### ISSUE TITLE
Potential room for consolidation in the "HTML sanitization" space.

### ISSUE THREAD

**Issue by dmitshur** [sourcegraph/htmlclean#1]
github.com/sourcegraph/htmlclean (/cc @sqs), please meet [github.com/microcosm-cc/bluemonday](https://github.com/microcosm-cc/bluemonday).

github.com/microcosm-cc/bluemonday (/cc @buro9), please meet [github.com/sourcegraph/htmlclean](https://github.com/sourcegraph/htmlclean).

I've learned about `htmlclean` from @sqs just now, and as suspected, it looks like these two libraries are very close in its objective, the approach (parse as HTML, keep whitelisted tags/attrs) and have similar origins (Matt Jibson's code in goread).

I just wanted to let both @sqs and @buro9 know about the similar efforts. Perhaps there's room for consolidation.

This same/similar functionality is also built in as a part of blackfriday (see https://github.com/russross/blackfriday/pull/69), which we've discussed in https://github.com/russross/blackfriday/issues/90 and came to the conclusion it may be a [good idea](https://github.com/russross/blackfriday/issues/90#issuecomment-48072929) to try and replace the use of built in code with a dedicated, potentially more well vetted library, which is something I'm working on now.

**Comment by dmitshur** [comment]
> This same/similar functionality is also built in as a part of blackfriday (see russross/blackfriday#69), which we've discussed in russross/blackfriday#90 and came to the conclusion it may be a good idea to try and replace the use of built in code with a dedicated, potentially more well vetted library, which is something I'm working on now.

That has been done now, so `blackfriday` points users to use `bluemonday` for HTML sanitization in [its README](https://github.com/russross/blackfriday#sanitize-untrusted-content).

**Comment by sqs** [comment]
Has anyone compared bluemonday and htmlclean to see if there are things that one is doing that the other is not? If bluemonday is superior, or if we can roll any features unique to htmlclean into bluemonday, I would be happy to EOL htmlclean and point people to bluemonday (which seems far more popular).

**Comment by dmitshur** [comment]
I haven't compared them in detail (I've only used `bluemonday` myself, which was before I discovered `htmlclean` existed), but I would suspect they're pretty similar.

I agree that doing that work (comparing them, and finding if there's anything that `htmlclean` does better than `bluemonday` and factoring it out into a PR for `bluemonday`, then EOLing `htmlclean`) is a good idea, since then there is one less library to maintain, etc. :) I think it's just a matter of finding a _configuration_ for `bluemonday` that produces identical or very similar results as `htmlclean.Clean`.

And the developers/maintainers of `bluemonday` do a great job of ensuring the correctness and high quality results of that library. It's already added to the [awesome-go list](https://github.com/avelino/awesome-go) so hopefully people looking for a Go library for html sanitization will find it.

**Comment by grafana-dee** [comment]
Just looked through.

Everything htmlclean does is covered by bluemonday.
Some of what bluemonday does is covered by htmlclean.

That said... the core logic of both is identical, because there's really not that many ways to attack this problem given the HTML lib.

If we're looking for split hairs, then the differences are:
- htmlclean whitelists attributes in general, rather than "these attributes on those elements"
- bluemonday validates formats of attributes and allows the difference to be expressed per element, for example the "value" attributes on a "meter" element should be a number and bluemonday will only whitelist that combination whilst allowing "value" on form elements to be strings and other things.
- bluemonday has deeper knowledge of URLs and how to handle certain scenarios (data URLs), as well as allowing developer supplied validation methods (for custom schema, i.e. for use with Android intents)
- bluemonday has a full test suite including the OWASP rules
- bluemonday allows for custom whitelist policies to be defined

The only thing I'd add is that htmlclean does have users, and just EOL might affect them. I wouldn't delete as I'm sure there are some people that didn't vendor. Perhaps just EOL by updating the readme to point to bluemonday and announcing a future point in time that you would delete.

I had found htmlclean before I created bluemonday and thought it very good, but the features I wanted to add and support required a full re-write focused on user defined whitelist policies. I was too used to the expressiveness of the OWASP Java HTML Sanitizer project and needed to translate a complex policy into something code could enforce. You can see that in bluemonday as the default UGCPolicy() that renders safe user generated content in forum posts and blog comments... an absolute cess pool of XSS.

**Comment by sqs** [comment]
Thanks! I will deprecate htmlclean and point people to bluemonday. (BTW, we mostly copied it from some other project originally.)

**Comment by dmitshur** [comment]
> Just looked through.
> 
> Everything htmlclean does is covered by bluemonday.
> Some of what bluemonday does is covered by htmlclean.

I'd like to go ahead and deprecate htmlclean so there's one less library to maintain.

I am seeing one feature that htmlclean does where I'm not seeing an equivalent ability in bluemonday. Perhaps I'm missing something, can you let me know @buro9 please?

Namely, [`htmlclean.Clean`](https://godoc.org/github.com/sourcegraph/htmlclean#Clean) takes a `*ur.URL` parameter `u`, and:

> Links are made relative to u, if non-nil.

I only see `AllowRelativeURLs` in bluemonday that controls if relative URLs are allowed. I don't see a way to rewrite relative URLs to be made relative to a base URL.

Is that ability available in bluemonday? Is it necessary/useful (perhaps it isn't, in that case this can be dropped)?

**Comment by grafana-dee** [comment]
This is interesting as it's something I do too in Microcosm: https://github.com/microcosm-cc/microcosm/blob/master/models/link_shortener.go#L212

That is code within a link shortener, where we do not shorten the link if it is internal but we do make the link absolute rather than the fully qualified link we encountered.

I have several pre-processing steps on the HTML that I generate from Markdown. This pre-processing handles link shortening, embedding rich media, embedding affiliate links, and changing fully qualified links to absolute "/path" links and so on.

I haven't included in the [bluemonday](https://github.com/microcosm-cc/bluemonday) code any of the pre-processing logic. I've kept bluemonday pure, dealing with a single thing only... ensuring that the HTML supplied to it is safe to be displayed on a website.

I don't feel this is necessary for bluemonday to do, but totally see that making a separate utility to handle some of the more common pre-processing tasks for HTML would be cool.

**Comment by grafana-dee** [comment]
BTW, were we to add such a feature, you'd need to bear in mind that the feature as described is an application design choice.

> Links are made relative to u, if non-nil.

If someone stores a piece of sanitised HTML in cache and uses that cached value on two different pages (i.e. a HTML summary of a story where the summary is shown on an index page as well as in the sidebar of other pages, as well as above the story on the detail page)... then any relative path would likely be wrong for some of those situations.

This is why in my case Microcosm favours changing URLs to absolute ones, the HTML can be cached and works on different pages.

Whether or not to use relative, absolute or fully qualified URLs is part of application design. Some may choose to use scheme relative // paths.

It seems to me, that this does demand a rules based processing library for transformation of URLs outside the scope of bluemonday or htmlclean. I resisted adding any of my own small requirements to bluemonday to keep it single-purposed and useful to all users... I'd do the same here.

**Comment by dmitshur** [comment]
@buro9, thanks for the detailed response.

> I resisted adding any of my own small requirements to bluemonday to keep it single-purposed and useful to all users... I'd do the same here.

I suspected that this functionality may not belong in the scope of `bluemonday`, and I completely agree with your hesitance to add it - please don't, as it would make the library worse, not better.

> Is that ability available in bluemonday? Is it necessary/useful (perhaps it isn't, in that case this can be dropped)?

I can see that it is the latter case.

I will work on moving that functionality into a pre-processing step as you suggested, and using `bluemonday` to sanitize the resulting HTML as a followup.

Thanks again!

> I don't feel this is necessary for bluemonday to do, but totally see that making a separate utility to handle some of the more common pre-processing tasks for HTML would be cool.

Yep, that makes sense. I think I'll start off by doing this internally, but as we get a better understanding of what's common and useful, it can be made exported into a library.

**Comment by grafana-dee** [comment]
We shouldn't continue this discussion here, but in effect https://github.com/microcosm-cc/bluemonday/issues/12 is also a pre-processing task.

Perhaps we should make another "bluemonday", mimicing much of the way that policies are constructed, but for these kinds of simple processing tasks.

Just the ones that are "change attribute value based on some easily checkable condition" and "add class to all element x".

I wouldn't expect a processor to do the more complex tasks such as "find this string in the HTML and replace that part of the DOM tree with this other DOM fragment" or even "transform this part of the DOM thus". Just a simple... change attributes, set attributes processor.

**Comment by dmitshur** [comment]
Following up on this old issue.

By now, I don't think the `htmlclean` package is used anywhere. We're not using it in Sourcegraph anymore (we are using `bluemonday` instead), and it has no known [public importers](https://godoc.org/github.com/sourcegraph/htmlclean?importers) on godoc.org. Whatever subtle different behavior `htmlclean` had is unlikely to be useful now, and can be re-created for specific needs of a new project.

Closing because this is resolved and there's nothing actionable left to do here.
